// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg1GVk45-G8vaB7Z56rUOh5Se5AJJFFGc',
    appId: '1:875432634144:web:f6b9edeb7757d8cf649945',
    messagingSenderId: '875432634144',
    projectId: 'cs311lab07-235da',
    authDomain: 'cs311lab07-235da.firebaseapp.com',
    storageBucket: 'cs311lab07-235da.appspot.com',
    measurementId: 'G-FWKCQLSQT5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy8LEWJaPOYYBsG09LTMvZSYNWK4PLPYU',
    appId: '1:875432634144:android:e32399b3d1ea3d58649945',
    messagingSenderId: '875432634144',
    projectId: 'cs311lab07-235da',
    storageBucket: 'cs311lab07-235da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtjpFsClld4DJ95bBuunvDbAJlPK58KqQ',
    appId: '1:875432634144:ios:4339af6976180b77649945',
    messagingSenderId: '875432634144',
    projectId: 'cs311lab07-235da',
    storageBucket: 'cs311lab07-235da.appspot.com',
    iosClientId: '875432634144-ggojfkn5j4hk3l3ce99kvgd44ahmre2m.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignment7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtjpFsClld4DJ95bBuunvDbAJlPK58KqQ',
    appId: '1:875432634144:ios:4339af6976180b77649945',
    messagingSenderId: '875432634144',
    projectId: 'cs311lab07-235da',
    storageBucket: 'cs311lab07-235da.appspot.com',
    iosClientId: '875432634144-ggojfkn5j4hk3l3ce99kvgd44ahmre2m.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignment7',
  );
}
